name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: myapp_test
          POSTGRES_USER: kebab
          POSTGRES_PASSWORD: 1234
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Set up database
        run: bundle exec rails db:setup
      # - name: Run FactoryBot setup
      #   run: bundle exec rails generate factory_bot:install
      - name: Run tests
        run: bundle exec rspec spec/policies

