name: deploy

on: [push]

jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [3.0.2]
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: myapp_test
          POSTGRES_USER: kebab
          POSTGRES_PASSWORD: 1234
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: Set up database
        run: bundle exec rails db:setup
      - name: Run tests
        run: bundle exec rspec
  deploy:
    runs-on: ubuntu-latest
    needs: rspec
    steps:
      - name: Result deploy
        run: echo Deploy good
